package model;
// Generated 18/07/2020 07:05:49 PM by Hibernate Tools 4.3.1



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int idCurso;
     private String nombre;
     private int horas;

    public Curso() {
    }

    public Curso(int idCurso, String nombre, int horas) {
       this.idCurso = idCurso;
       this.nombre = nombre;
       this.horas = horas;
    }
   
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getHoras() {
        return this.horas;
    }
    
    public void setHoras(int horas) {
        this.horas = horas;
    }




}


